name: Sync To Gitee
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # 每周日同步一次，对应文档 
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule
    - cron: '2,10 4,5 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "https://github.com/lhy0315cn/jd_my.git"
          destination-repo: "git@gitee.com:liuliangji/sync_script.git"
